### ISSUE TITLE
运行以后，报错，可以指教一下吗？

### ISSUE THREAD

**Issue by kingdeewang** [bojone/margin-softmax#3]
Tensor("cu_dnngru_1/strided_slice_12:0", shape=(?, 128), dtype=float32)
Epoch 1/25
2018-08-03 16:49:43.710397: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "sent_sim.py", line 88, in <module>
    epochs=epochs)
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/keras/engine/training.py", line 1705, in fit
    validation_steps=validation_steps)
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/keras/engine/training.py", line 1235, in _fit_loop
    outs = f(ins_batch)
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2476, in __call__
    session = get_session()
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 192, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/wel/anaconda3/envs/tensorflow_py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: cu_dnngru_1/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="gru", seed=87654321, seed2=0](cu_dnngru_1/transpose, cu_dnngru_1/ExpandDims_1, cu_dnngru_1/Const_1, cu_dnngru_1/concat)]]

Caused by op u'cu_dnngru_1/CudnnRNN', defined at:
  File "sent_sim.py", line 70, in <module>
    x = CuDNNGRU(word_size)(x_embedded)

**Comment by bojone** [comment]
没碰到过，我也无解...

**Comment by bojone** [comment]
我大概清楚了，CuDNNGRU需要的是gpu版本的tensorflow，如果不是，请改为GRU
